---
title: "Fundamental of Statisctic Descriptive Part 1"
author: "M Adi Setiawan"
output: html_document
date: "2023-10-09"
---

> disclaimer : tulisan ini diadospsi dari materi dari indonesia belajar

# A. Dasar Eksperimen dan Desain Eksperimen

* definisi studi eksperimen : suatu aktivitas pengamatan dimana objek yang diamati diberikan suatu treament khusus sementara objek lainnya tidak (placeboo)

* hal-hal yang perlu diamati dalam melakukan studi eksperimen (control, randomisation, replication):

  1. Control (kendali) terbagi menjadi 2 : treatment group (objek yang diberikan treament khusus) dan control group (objek yang tidak diberikan treatment khusus sering disebut dengan placeboo). selain itu pada kontrol juga ada yang disebut dengan bliding (subjek tidak mengetahui apakah dirinya termasuk dalam treatment group) dan double bliding (peneliti dan subjek tidak mengetahui treatment group)
  
  2. Randomisation (Pengacakan) : penentuan objek mana yang akan dikelompokkan sebagai treatment group atau control group. metode yang dapat digunakan adalah randomised blocked design, dimana objek terlebih dahulu dikelompokkan berdasarkan kesamaan karakteristik (ex : rentang usia, jenis kelamin dll). kemudian, objek yang telah dikelompokkan tadi di pilih secara acak untuk dikelompokkan sebagai treatment group atau control group.
  
  3. Replication (Replikasi) :pengulangan eksperimen dengan kondisi yang mirip dengan tujuan meningkatkan validitas. replikasi melibatkan objek eksperimen yang berbeda sehingga bisa memperbesar ukuran sample (sample size).
  
* ada beberapa tantangan dalam melakukan experimental study :

  1. confounding/lurking variable : faktor eskternal yang dapat berpotensi mempengaruhi hasil eksperimen.
  
  2. placeboo effect : control group memberikan hasil yang sama (positif) dengan treatment group
  
  3. hawthrone effect : perubahan perilaku dari objek ketika mengetahui dirinya terlibat dalam eksperimen
  
# B. Jenis Pengumpulan Data

* ada 2 jenis pengumpulan data : census dan sampling

* sampling : pengumupulan data dari sub populasi sehingga sifatnya kurang lengkap. sehingga perlu diperhatikan bahwa sampel yang baik adalah sampel yang dapat merepresentasikan keseluruhan populasi.

* ada 2 jenis sampling :
  
  1. sampling with replacement : jenis sampling yang memungkinkan objek dapat terpilih lebih dari 1 kali.
  
  2. sampling without replacement : jenis sampling yang tidak memungkinkan objek dapat terpilih lebih dari 1 kali atau objek hanya dapat terpilih maksimal 1 kali.

* beberapa metode sampling :
  
  1. Simple Random Sampling : teknik pengumpulan data yang dilakukan secara acak dimana setiap populasi memiliki peluang yang sama untuk dapat terpilih sebagai anggota sampel.
  
  contoh : suatu kelas berisi 400 siswa akan dilakukan pemilihan acak dimana tiap siswa memiliki peluang yang sama untuk dapat dilibatkan dalam suatu survey. untuk mengenerate simple random sampling, dilakukan pemilihan 10 nomor yang mewakili siswa pada rentang no 1 dan 400.
  
  2. Strafied Sampling : teknik pengumpulan data secara acak dengan terlebih dahulu membagi anggota populasi kedalam beberapa kelompok/klasifikasi berdasarkan kesamaan karakteristik misal rentang usia, jenis kelamin dll. kelompok yang telah diklasifikasikan ini sering disebut dengan **strata**. Selanjutnya, anggota dari tiap strata dipilih secara acak untuk dijadikan sample. perlu diperhatikan bahwa sampling dilakukan haruslah proporsial dengan porsinya dalam populasi.
  
  contoh : akan dilakukan survey pada 100 mahasiswa di suatu universitas terkait preferensi memilih menu makan siang. didapati bahwa universitas tersebut memiliki total 3500 mahasiswa dengan sebaran 55% laki-laki dan 45 % perempuan. berdasarkan teknik stratified sampling dipilihlah 55 orang mahasiswa dan 45 mahasiswi untuk mengikuti survey tersebut.
  
  3. Cluster Sampling : sama seperti strafied sampling, tetapi cluster sampling mengelompokkan objek dalam populasi berdasarkan kesamaan yang sudah terbentuk (seperti : geografis, kecamatan, kelurahan etc)
  
  4. Systematic Sampling : teknik pengumpulan data berdasarkan interval tertentu. baik diterapkan jika ditemui adanya pola yang konsisten
  
  contoh : dilakukan survey kepuasan pelanggan di suatu minimarket terhadap setiap pengunjung dengan interval kedatangan 10. dengan kata lain, jika saat ini pengujung yang dijadikan sample adalah pengunjung ke-5, maka sample selanjutnya adalah pengunjung ke-15 dst (25,35,45....).
  
  5. Convenience Sampling : teknik pengumpulan data yang bisa dibilang asal atau sembrono dan hanya berorientasi pada kemudahan.
  
  contohnya : jika terdapat 7 kecamatan, dan akan dilakukan survey pada daerah tersebut. hanya dipilih 1 kecamatan yang memiliki populasi yang besar untuk mewakili daerah tsb dalam kegiatan survey.

# C. Distribusi & Frekuensi

* beberapa karakteristik yang biasanya digunakan untuk mendeskripsikan data : titik tengah data (center), variasi/sebaran (variability/spread) dan bentuk data (shape)

* salah satu cara yang paling mudah untuk mengelola data adalah **distribusi frekuensi (frequency distribution)**

* definisi distribusi frekuensi adalah bentuk pengelolaan data dimana data dikelompokkan ke dalam beberapa kelas (classes) berdasarkan interval tertentu.

* jumlah data yang muncul di tiap-tiap kelas disebut dengan frekuensi dari kelas (class frequency)

* langkah - langkah membuat distribusi frekuensi :
  
  1. tentukan jumlah kelas dataset tersebut, dapat dilakukan dengan pendekatan formula berikut : 1 + 3.33 * log n , dimana n adalah jumlah data
  
  2. tentukan nilai min dan max dataset tsb
  
  3. tentukan interval / range dataset tsb, formula : max - min
  
  4. tentukan class width / interval tiap kelas / range tiap kelas dengan formula : (max-min)/jumlah kelas
  
  5. buat tiap kelas sesuai dengan n class (jumlah kelas) dan nilai class width nya dengan nilai awal adalah min.
  
  contoh : berikut merupakan suatu dataset harga keyboard dalam satuan ribu

```{r create frequency distribution, echo=TRUE}

keyboard_price <- c (128,100,180,150,200,90,340,105,85,270,
                     200,65,230,150,150,120,130,80,230,200,110,
                     126,170,132,140,112,90,340,170,190)

# 0. urutkan dataset
sort_dataset <- sort(keyboard_price)

# 1. menentukan jumlah kelas
n_data <- length(sort_dataset)

n_class <- round(1 + 3.33*log(n_data), digits = 0)

# 2. menentukan nilai min dan max

min_x <- min(sort_dataset)
max_x <- max(sort_dataset)

# 3. menentukan range
range_x <- max_x - min_x

# 4. menentukan class_width

class_width <-  round(range_x / n_class, digits = 0)

# 5. buat kelas distribusi

breaks <- seq (min_x,350,class_width)

dist_class <- cut(sort_dataset, breaks = breaks, rigth = F )

tabel_dist <- table (dist_class)
tabel_dist

```
  
# D. Measure of Central Tendency dalam stastika & bentuk distribusi

## D.1 Central of Tendency
  
  * definisi : Pengukuran nilai yang merepresentasikan nilai tipikal atau nilai sentral dari suatu dataset.
  
  * bentuk umum : mean, median dan mode
  
    * mean : nilai rata-rata, penjumlahan dari semua dataset dibagi dengan banyaknya entri data pada dataset.
    
    * median : nilai tengah, nilai yang tepat berada di tengah suatu dataset yang telah diurutkan. jika dataset ganjil, makan median adalah data yang tepat berada ditengah. sedangkan, jika dataset genap, maka median adalah rerata dua nilai yang berada ditengah
  
  * mode / modus : nilai yang paling sering muncul, nilai yang frekuensi kemunculannya paling banyak pada suatu dataset. suatu dataset dapat memilki lebih dari suatu modus.sebaliknya, suatu dataset juga memungkinkan tidak memiliki mode.


  